package org.sportstechsolutions.apitacticsapp.model

enum class TacticalAction(val phase: PhaseOfPlay) {
    // --- OFFENSIVE ---
    RECEIVING_1ST_TOUCH(PhaseOfPlay.OFFENSIVE),
    PASSING_DISTRIBUTION(PhaseOfPlay.OFFENSIVE),
    DRIBBLING_CARRYING(PhaseOfPlay.OFFENSIVE),
    FINISHING_STRIKING(PhaseOfPlay.OFFENSIVE),
    SHIELDING_RETENTION(PhaseOfPlay.OFFENSIVE),
    SUPPORT_PLAY_ANGLES(PhaseOfPlay.OFFENSIVE),
    PENETRATING_RUNS(PhaseOfPlay.OFFENSIVE),
    SPACE_CREATION(PhaseOfPlay.OFFENSIVE),

    // --- DEFENSIVE ---
    MARKING(PhaseOfPlay.DEFENSIVE),
    DELAYING_JOCKEYING(PhaseOfPlay.DEFENSIVE),
    TACKLING_DUELING(PhaseOfPlay.DEFENSIVE),
    BLOCKING_INTERCEPTING(PhaseOfPlay.DEFENSIVE),
    COVER_BALANCE(PhaseOfPlay.DEFENSIVE),
    UNIT_SHIFTING(PhaseOfPlay.DEFENSIVE),

    // --- OFFENSIVE TRANSITION (Attacking Transition) ---
    COUNTER_ATTACKING(PhaseOfPlay.OFFENSIVE_TRANSITION),
    BREAKING_LINES(PhaseOfPlay.OFFENSIVE_TRANSITION),
    FORWARD_PASSING(PhaseOfPlay.OFFENSIVE_TRANSITION),

    // --- DEFENSIVE TRANSITION (Defending Transition) ---
    PRESSING(PhaseOfPlay.DEFENSIVE_TRANSITION),
    RECOVERY_RUNS(PhaseOfPlay.DEFENSIVE_TRANSITION),
    COUNTER_PRESSING(PhaseOfPlay.DEFENSIVE_TRANSITION),
    REORGANIZING_SHAPE(PhaseOfPlay.DEFENSIVE_TRANSITION)
}