# --- BASE SETTINGS ---
spring.application.name=ApiTacticsApp
server.port=${PORT:8085}

# Default to dev profile if SPRING_PROFILES_ACTIVE is not explicitly set
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# --- UNIVERSAL BEHAVIORS ---
server.compression.enabled=true
server.compression.mime-types=application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript,text/javascript
server.compression.min-response-size=2048

# Database Driver & JPA Universal Settings
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.default_batch_fetch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true