# --- PROD DATABASE ---
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# --- PROD SECURITY ---
cors.allowed-origins=${CORS_ALLOWED_ORIGINS}
jwt.secret=${JWT_SECRET}


# --- PROD BEHAVIOR (Safe) ---
# STRICTLY validates the schema. Never alters tables in production.
spring.jpa.hibernate.ddl-auto=validate